# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/190/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/190/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/stepan/C++/TpSQL

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/stepan/C++/TpSQL

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/clion/190/bin/cmake/linux/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/190/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/stepan/C++/TpSQL/CMakeFiles /home/stepan/C++/TpSQL//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/stepan/C++/TpSQL/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TpSQL

# Build rule for target.
TpSQL: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TpSQL
.PHONY : TpSQL

# fast build rule for target.
TpSQL/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TpSQL.dir/build.make CMakeFiles/TpSQL.dir/build
.PHONY : TpSQL/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TpSQL.dir/build.make CMakeFiles/TpSQL.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TpSQL.dir/build.make CMakeFiles/TpSQL.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TpSQL.dir/build.make CMakeFiles/TpSQL.dir/main.cpp.s
.PHONY : main.cpp.s

project/src/Table.o: project/src/Table.cpp.o
.PHONY : project/src/Table.o

# target to build an object file
project/src/Table.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TpSQL.dir/build.make CMakeFiles/TpSQL.dir/project/src/Table.cpp.o
.PHONY : project/src/Table.cpp.o

project/src/Table.i: project/src/Table.cpp.i
.PHONY : project/src/Table.i

# target to preprocess a source file
project/src/Table.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TpSQL.dir/build.make CMakeFiles/TpSQL.dir/project/src/Table.cpp.i
.PHONY : project/src/Table.cpp.i

project/src/Table.s: project/src/Table.cpp.s
.PHONY : project/src/Table.s

# target to generate assembly for a file
project/src/Table.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TpSQL.dir/build.make CMakeFiles/TpSQL.dir/project/src/Table.cpp.s
.PHONY : project/src/Table.cpp.s

project/src/Tcmd.o: project/src/Tcmd.cpp.o
.PHONY : project/src/Tcmd.o

# target to build an object file
project/src/Tcmd.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TpSQL.dir/build.make CMakeFiles/TpSQL.dir/project/src/Tcmd.cpp.o
.PHONY : project/src/Tcmd.cpp.o

project/src/Tcmd.i: project/src/Tcmd.cpp.i
.PHONY : project/src/Tcmd.i

# target to preprocess a source file
project/src/Tcmd.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TpSQL.dir/build.make CMakeFiles/TpSQL.dir/project/src/Tcmd.cpp.i
.PHONY : project/src/Tcmd.cpp.i

project/src/Tcmd.s: project/src/Tcmd.cpp.s
.PHONY : project/src/Tcmd.s

# target to generate assembly for a file
project/src/Tcmd.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TpSQL.dir/build.make CMakeFiles/TpSQL.dir/project/src/Tcmd.cpp.s
.PHONY : project/src/Tcmd.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TpSQL"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... project/src/Table.o"
	@echo "... project/src/Table.i"
	@echo "... project/src/Table.s"
	@echo "... project/src/Tcmd.o"
	@echo "... project/src/Tcmd.i"
	@echo "... project/src/Tcmd.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

