# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16
# Собран Makefile
# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/stepan/C++/techonparkproject

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/stepan/C++/techonparkproject

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/stepan/C++/techonparkproject/CMakeFiles /home/stepan/C++/techonparkproject/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/stepan/C++/techonparkproject/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TpSQL

# Build rule for target.
TpSQL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TpSQL
.PHONY : TpSQL

# fast build rule for target.
TpSQL/fast:
	$(MAKE) -f CMakeFiles/TpSQL.dir/build.make CMakeFiles/TpSQL.dir/build
.PHONY : TpSQL/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/TpSQL.dir/build.make CMakeFiles/TpSQL.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/TpSQL.dir/build.make CMakeFiles/TpSQL.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/TpSQL.dir/build.make CMakeFiles/TpSQL.dir/main.cpp.s
.PHONY : main.cpp.s

project/src/Table.o: project/src/Table.cpp.o

.PHONY : project/src/Table.o

# target to build an object file
project/src/Table.cpp.o:
	$(MAKE) -f CMakeFiles/TpSQL.dir/build.make CMakeFiles/TpSQL.dir/project/src/Table.cpp.o
.PHONY : project/src/Table.cpp.o

project/src/Table.i: project/src/Table.cpp.i

.PHONY : project/src/Table.i

# target to preprocess a source file
project/src/Table.cpp.i:
	$(MAKE) -f CMakeFiles/TpSQL.dir/build.make CMakeFiles/TpSQL.dir/project/src/Table.cpp.i
.PHONY : project/src/Table.cpp.i

project/src/Table.s: project/src/Table.cpp.s

.PHONY : project/src/Table.s

# target to generate assembly for a file
project/src/Table.cpp.s:
	$(MAKE) -f CMakeFiles/TpSQL.dir/build.make CMakeFiles/TpSQL.dir/project/src/Table.cpp.s
.PHONY : project/src/Table.cpp.s

project/src/auxiliary_func.o: project/src/auxiliary_func.cpp.o

.PHONY : project/src/auxiliary_func.o

# target to build an object file
project/src/auxiliary_func.cpp.o:
	$(MAKE) -f CMakeFiles/TpSQL.dir/build.make CMakeFiles/TpSQL.dir/project/src/auxiliary_func.cpp.o
.PHONY : project/src/auxiliary_func.cpp.o

project/src/auxiliary_func.i: project/src/auxiliary_func.cpp.i

.PHONY : project/src/auxiliary_func.i

# target to preprocess a source file
project/src/auxiliary_func.cpp.i:
	$(MAKE) -f CMakeFiles/TpSQL.dir/build.make CMakeFiles/TpSQL.dir/project/src/auxiliary_func.cpp.i
.PHONY : project/src/auxiliary_func.cpp.i

project/src/auxiliary_func.s: project/src/auxiliary_func.cpp.s

.PHONY : project/src/auxiliary_func.s

# target to generate assembly for a file
project/src/auxiliary_func.cpp.s:
	$(MAKE) -f CMakeFiles/TpSQL.dir/build.make CMakeFiles/TpSQL.dir/project/src/auxiliary_func.cpp.s
.PHONY : project/src/auxiliary_func.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... TpSQL"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... project/src/Table.o"
	@echo "... project/src/Table.i"
	@echo "... project/src/Table.s"
	@echo "... project/src/auxiliary_func.o"
	@echo "... project/src/auxiliary_func.i"
	@echo "... project/src/auxiliary_func.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

